# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        ('commissions', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('services', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionadjustment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_adjustments', to='staff.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payouts', to='accounts.localuser', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payouts', to='accounts.localuser', verbose_name='Paid By'),
        ),
        migrations.AddField(
            model_name='commissionpayout',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_payouts', to='staff.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddField(
            model_name='commissionadjustment',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments_list', to='commissions.commissionpayout', verbose_name='Payout'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='inventory.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='services.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_rules', to='staff.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AlterUniqueTogether(
            name='commissionssettings',
            unique_together={('hub_id',)},
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to='appointments.appointment', verbose_name='Appointment'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to='accounts.localuser', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='commissions.commissionpayout', verbose_name='Payout'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='commissions.commissionrule', verbose_name='Rule'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to='sales.sale', verbose_name='Sale'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_transactions', to='staff.staffmember', verbose_name='Staff Member'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['hub_id', 'staff_id', 'status'], name='commissions_hub_id_a21c41_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['hub_id', 'transaction_date'], name='commissions_hub_id_abc224_idx'),
        ),
    ]
